[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.filesystem = littlefs
lib_ldf_mode = deep
lib_deps =
	https://github.com/me-no-dev/ESPAsyncWebServer.git
	bblanchon/ArduinoJson@^7.1.0
	AsyncTCP
	tanakamasayuki/TensorFlowLite_ESP32@^1.0.0
build_flags =
	-D CORE_DEBUG_LEVEL=0