Add-Type -AssemblyName System.Drawing
$theme = @{ bg=[System.Drawing.Color]::White; ink=[System.Drawing.Color]::FromArgb(33,37,41); muted=[System.Drawing.Color]::FromArgb(108,117,125); border=[System.Drawing.Color]::FromArgb(52,58,64); line=[System.Drawing.Color]::FromArgb(206,212,218); blue=[System.Drawing.Color]::FromArgb(24,119,242); green=[System.Drawing.Color]::FromArgb(26,127,55); orange=[System.Drawing.Color]::FromArgb(230,119,0); red=[System.Drawing.Color]::FromArgb(192,57,43); purple=[System.Drawing.Color]::FromArgb(111,66,193); lblue=[System.Drawing.Color]::FromArgb(232,242,255); lgreen=[System.Drawing.Color]::FromArgb(234,247,238); lorange=[System.Drawing.Color]::FromArgb(255,245,230); lred=[System.Drawing.Color]::FromArgb(253,237,236); lgray=[System.Drawing.Color]::FromArgb(248,249,250) }
$out = Join-Path (Resolve-Path .) 'assets\\png'
function F([float]$s,[string]$style='Regular'){ New-Object System.Drawing.Font('Segoe UI',$s,[System.Drawing.FontStyle]::$style) }
function Canvas([int]$w=2200,[int]$h=1300){ $bmp=New-Object System.Drawing.Bitmap $w,$h; $g=[System.Drawing.Graphics]::FromImage($bmp); $g.SmoothingMode='AntiAlias'; $g.InterpolationMode='HighQualityBicubic'; $g.PixelOffsetMode='HighQuality'; $g.TextRenderingHint='AntiAliasGridFit'; $g.Clear($theme.bg); @{bmp=$bmp;g=$g;w=$w;h=$h} }
function PathRR([float]$x,[float]$y,[float]$w,[float]$h,[float]$r){ $p=New-Object System.Drawing.Drawing2D.GraphicsPath; $d=$r*2; $p.AddArc($x,$y,$d,$d,180,90); $p.AddArc($x+$w-$d,$y,$d,$d,270,90); $p.AddArc($x+$w-$d,$y+$h-$d,$d,$d,0,90); $p.AddArc($x,$y+$h-$d,$d,$d,90,90); $p.CloseFigure(); $p }
function CenterLines($g,[string[]]$lines,[float]$x,[float]$y,[float]$w,[float]$h,$font,$brush){ $gap=10; $sizes=@(); $total=0; foreach($line in $lines){ $s=$g.MeasureString($line,$font); $sizes += $s; $total += [Math]::Ceiling($s.Height) }; $total += (($lines.Count-1)*$gap); $cy = $y + (($h-$total)/2); for($i=0;$i -lt $lines.Count;$i++){ $line=$lines[$i]; $s=$sizes[$i]; $lx = $x + (($w-$s.Width)/2); $g.DrawString($line,$font,$brush,[float]$lx,[float]$cy); $cy += [Math]::Ceiling($s.Height) + $gap } }
function LeftLines($g,[string[]]$lines,[float]$x,[float]$y,$font,$brush){ $gap=8; $cy=$y; foreach($line in $lines){ $g.DrawString($line,$font,$brush,$x,$cy); $cy += [Math]::Ceiling(($g.MeasureString($line,$font)).Height) + $gap } }
function Title($g,$idx,$title,$sub){ $b=New-Object System.Drawing.SolidBrush $theme.ink; $m=New-Object System.Drawing.SolidBrush $theme.muted; $g.DrawString("$idx. $title",(F 34 'Bold'),$b,72,42); $g.DrawString($sub,(F 19),$m,72,102); $b.Dispose(); $m.Dispose() }
function Panel($g,[float]$x,[float]$y,[float]$w,[float]$h,[string]$title,[string[]]$lines,$fillColor,$borderColor){ $p=PathRR $x $y $w $h 26; $fill=New-Object System.Drawing.SolidBrush $fillColor; $pen=New-Object System.Drawing.Pen $borderColor,3; $b=New-Object System.Drawing.SolidBrush $theme.ink; $g.FillPath($fill,$p); $g.DrawPath($pen,$p); CenterLines $g @($title) $x ($y+10) $w 40 (F 22 'Bold') $b; LeftLines $g $lines ($x+28) ($y+58) (F 18) $b; $b.Dispose(); $pen.Dispose(); $fill.Dispose(); $p.Dispose() }
function Badge($g,[float]$cx,[float]$cy,[string]$text){ $font=F 18 'Bold'; $probe=$g.MeasureString($text,$font); $w=[Math]::Max(220,[Math]::Ceiling($probe.Width)+40); $h=50; $x=$cx-($w/2); $y=$cy-($h/2); $p=PathRR $x $y $w $h 18; $fill=New-Object System.Drawing.SolidBrush $theme.lgray; $pen=New-Object System.Drawing.Pen $theme.border,2; $b=New-Object System.Drawing.SolidBrush $theme.ink; $g.FillPath($fill,$p); $g.DrawPath($pen,$p); CenterLines $g @($text) $x ($y+4) $w ($h-8) $font $b; $b.Dispose();$pen.Dispose();$fill.Dispose();$p.Dispose() }
function Arrow($g,[float]$x1,[float]$y1,[float]$x2,[float]$y2,$color,[string]$style='Solid'){ $pen=New-Object System.Drawing.Pen $color,4; if($style -eq 'Dash'){ $pen.DashStyle='Dash' }; $cap=New-Object System.Drawing.Drawing2D.AdjustableArrowCap(7,9,$true); $pen.CustomEndCap=$cap; $g.DrawLine($pen,$x1,$y1,$x2,$y2); $pen.Dispose(); $cap.Dispose() }
function Decision($g,[float]$cx,[float]$cy,[float]$w,[float]$h,[string[]]$lines,$fillColor,$borderColor){ $pts = [System.Drawing.PointF[]]@((New-Object System.Drawing.PointF -ArgumentList ([float]$cx),([float]($cy-($h/2)))),(New-Object System.Drawing.PointF -ArgumentList ([float]($cx+($w/2))),([float]$cy)),(New-Object System.Drawing.PointF -ArgumentList ([float]$cx),([float]($cy+($h/2)))),(New-Object System.Drawing.PointF -ArgumentList ([float]($cx-($w/2))),([float]$cy))); $fill=New-Object System.Drawing.SolidBrush $fillColor; $pen=New-Object System.Drawing.Pen $borderColor,3; $b=New-Object System.Drawing.SolidBrush $theme.ink; $g.FillPolygon($fill,$pts); $g.DrawPolygon($pen,$pts); CenterLines $g $lines ($cx-($w/2)+24) ($cy-($h/2)+18) ($w-48) ($h-36) (F 19 'Bold') $b; $b.Dispose();$pen.Dispose();$fill.Dispose() }
function Save($c,$name){ $path=Join-Path $out $name; $c.bmp.Save($path,[System.Drawing.Imaging.ImageFormat]::Png); $c.g.Dispose(); $c.bmp.Dispose() }
function Lane($g,[float]$x,[float]$y,[float]$w,[float]$h,[string]$title){ $head=68; $pen=New-Object System.Drawing.Pen $theme.border,2.5; $hb=New-Object System.Drawing.SolidBrush $theme.lblue; $bb=New-Object System.Drawing.SolidBrush $theme.lgray; $g.FillRectangle($bb,$x,$y+$head,$w,$h-$head); $g.FillRectangle($hb,$x,$y,$w,$head); $g.DrawRectangle($pen,$x,$y,$w,$h); $d=New-Object System.Drawing.Pen $theme.line,2; $d.DashStyle='Dash'; $g.DrawLine($d,$x+($w/2),$y+$head,$x+($w/2),$y+$h); $b=New-Object System.Drawing.SolidBrush $theme.ink; CenterLines $g @($title) $x ($y+8) $w 52 (F 20 'Bold') $b; $b.Dispose();$d.Dispose();$bb.Dispose();$hb.Dispose();$pen.Dispose() }
function TableDraw($g,[float]$x,[float]$y,[float[]]$widths,[string[]]$headers,[object[]]$rows,[int]$rowH=84){ $headFont=F 20 'Bold'; $bodyFont=F 18; $pen=New-Object System.Drawing.Pen $theme.border,2; $hb=New-Object System.Drawing.SolidBrush $theme.lblue; $ab=New-Object System.Drawing.SolidBrush $theme.lgray; $wb=New-Object System.Drawing.SolidBrush $theme.bg; $ib=New-Object System.Drawing.SolidBrush $theme.ink; $cx=$x; for($i=0;$i -lt $headers.Count;$i++){ $g.FillRectangle($hb,$cx,$y,$widths[$i],$rowH); $g.DrawRectangle($pen,$cx,$y,$widths[$i],$rowH); CenterLines $g @($headers[$i]) ($cx+10) ($y+6) ($widths[$i]-20) ($rowH-12) $headFont $ib; $cx += $widths[$i] }
 for($r=0;$r -lt $rows.Count;$r++){ $ry=$y+$rowH+($r*$rowH); $brush= if($r%2 -eq 0){$wb}else{$ab}; $cx=$x; for($c=0;$c -lt $headers.Count;$c++){ $g.FillRectangle($brush,$cx,$ry,$widths[$c],$rowH); $g.DrawRectangle($pen,$cx,$ry,$widths[$c],$rowH); CenterLines $g @([string]$rows[$r][$c]) ($cx+10) ($ry+8) ($widths[$c]-20) ($rowH-16) $bodyFont $ib; $cx += $widths[$c] } }
 $ib.Dispose();$wb.Dispose();$ab.Dispose();$hb.Dispose();$pen.Dispose() }



