Add-Type -AssemblyName System.Drawing
$theme = @{ bg=[System.Drawing.Color]::White; ink=[System.Drawing.Color]::FromArgb(33,37,41); border=[System.Drawing.Color]::FromArgb(52,58,64); blue=[System.Drawing.Color]::FromArgb(24,119,242); green=[System.Drawing.Color]::FromArgb(26,127,55); orange=[System.Drawing.Color]::FromArgb(230,119,0); red=[System.Drawing.Color]::FromArgb(192,57,43); lblue=[System.Drawing.Color]::FromArgb(232,242,255); lgreen=[System.Drawing.Color]::FromArgb(234,247,238); lorange=[System.Drawing.Color]::FromArgb(255,245,230); lred=[System.Drawing.Color]::FromArgb(253,237,236); lgray=[System.Drawing.Color]::FromArgb(248,249,250) }
$out = Join-Path (Resolve-Path .) 'assets\\png'
function F([float]$s,[string]$style='Regular'){ New-Object System.Drawing.Font('Segoe UI',$s,[System.Drawing.FontStyle]::$style) }
function Canvas(){ $bmp=New-Object System.Drawing.Bitmap 2200,1300; $g=[System.Drawing.Graphics]::FromImage($bmp); $g.SmoothingMode='AntiAlias'; $g.InterpolationMode='HighQualityBicubic'; $g.PixelOffsetMode='HighQuality'; $g.TextRenderingHint='AntiAliasGridFit'; $g.Clear($theme.bg); @{bmp=$bmp;g=$g} }
function PathRR([float]$x,[float]$y,[float]$w,[float]$h,[float]$r){ $p=New-Object System.Drawing.Drawing2D.GraphicsPath; $d=$r*2; $p.AddArc($x,$y,$d,$d,180,90); $p.AddArc($x+$w-$d,$y,$d,$d,270,90); $p.AddArc($x+$w-$d,$y+$h-$d,$d,$d,0,90); $p.AddArc($x,$y+$h-$d,$d,$d,90,90); $p.CloseFigure(); $p }
function CenterLines($g,[string[]]$lines,[float]$x,[float]$y,[float]$w,[float]$h,$font,$brush){ $gap=10; $sizes=@(); $total=0; foreach($line in $lines){ $s=$g.MeasureString($line,$font); $sizes += $s; $total += [Math]::Ceiling($s.Height) }; $total += (($lines.Count-1)*$gap); $cy = $y + (($h-$total)/2); for($i=0;$i -lt $lines.Count;$i++){ $line=$lines[$i]; $s=$sizes[$i]; $lx = $x + (($w-$s.Width)/2); $g.DrawString($line,$font,$brush,[float]$lx,[float]$cy); $cy += [Math]::Ceiling($s.Height) + $gap } }
function Title($g,$idx,$title,$sub){ $b=New-Object System.Drawing.SolidBrush $theme.ink; $m=New-Object System.Drawing.SolidBrush ([System.Drawing.Color]::FromArgb(108,117,125)); $g.DrawString("$idx. $title",(F 34 'Bold'),$b,72,42); $g.DrawString($sub,(F 19),$m,72,102); $b.Dispose(); $m.Dispose() }
function Panel($g,[float]$x,[float]$y,[float]$w,[float]$h,[string]$title,[string[]]$lines,$fillColor,$borderColor){ $p=PathRR $x $y $w $h 26; $fill=New-Object System.Drawing.SolidBrush $fillColor; $pen=New-Object System.Drawing.Pen $borderColor,3; $b=New-Object System.Drawing.SolidBrush $theme.ink; $g.FillPath($fill,$p); $g.DrawPath($pen,$p); CenterLines $g @($title) $x ($y+20) $w 40 (F 24 'Bold') $b; CenterLines $g $lines ($x+18) ($y+68) ($w-36) ($h-86) (F 20) $b; $b.Dispose(); $pen.Dispose(); $fill.Dispose(); $p.Dispose() }
function Badge($g,[float]$cx,[float]$cy,[string]$text){ $font=F 18 'Bold'; $probe=$g.MeasureString($text,$font); $w=[Math]::Max(220,[Math]::Ceiling($probe.Width)+40); $h=50; $x=$cx-($w/2); $y=$cy-($h/2); $p=PathRR $x $y $w $h 18; $fill=New-Object System.Drawing.SolidBrush $theme.lgray; $pen=New-Object System.Drawing.Pen $theme.border,2; $b=New-Object System.Drawing.SolidBrush $theme.ink; $g.FillPath($fill,$p); $g.DrawPath($pen,$p); CenterLines $g @($text) $x ($y+4) $w ($h-8) $font $b; $b.Dispose();$pen.Dispose();$fill.Dispose();$p.Dispose() }
function Arrow($g,[float]$x1,[float]$y1,[float]$x2,[float]$y2,$color,[string]$style='Solid'){ $pen=New-Object System.Drawing.Pen $color,4; if($style -eq 'Dash'){ $pen.DashStyle='Dash' }; $cap=New-Object System.Drawing.Drawing2D.AdjustableArrowCap(7,9,$true); $pen.CustomEndCap=$cap; $g.DrawLine($pen,$x1,$y1,$x2,$y2); $pen.Dispose(); $cap.Dispose() }
function Save($c,$name){ $path=Join-Path $out $name; $c.bmp.Save($path,[System.Drawing.Imaging.ImageFormat]::Png); $c.g.Dispose(); $c.bmp.Dispose() }
$c=Canvas; $g=$c.g; Title $g '01' 'Kiến trúc tổng thể' 'Hai sender gửi dữ liệu về một receiver; receiver đóng vai trò gateway lên CoreIoT.'; Panel $g 120 220 380 260 'Sender A' @('Mô phỏng cảm biến','Suy luận TinyML tại edge','Web UI cục bộ','Gửi telemetry qua TCP') $theme.lgreen $theme.green; Panel $g 120 760 380 240 'Sender B' @('Mô phỏng cảm biến độc lập','Threshold riêng','Nhận config và gửi ACK','Gửi telemetry qua TCP') $theme.lgreen $theme.green; Panel $g 760 260 520 360 'Receiver gateway' @('TCP server nhận nhiều sender','Quản lý known / unknown device','Đồng bộ threshold hai chiều','Web UI quản trị','MQTT gateway lên CoreIoT') $theme.lblue $theme.blue; Panel $g 1520 300 520 280 'CoreIoT / Cloud' @('Lưu telemetry','Lưu attribute threshold','Hiển thị dashboard','Gọi RPC từ xa') $theme.lorange $theme.orange; Panel $g 760 760 520 180 'Control plane' @('UI receiver hoặc RPC cloud','Tạo gói config','Sender phản hồi config_ack') $theme.lred $theme.red; Arrow $g 500 340 760 380 $theme.green; Badge $g 630 300 'Telemetry JSON'; Arrow $g 500 860 760 520 $theme.green; Badge $g 630 690 'Telemetry JSON'; Arrow $g 1280 420 1520 420 $theme.blue; Badge $g 1400 365 'MQTT gateway'; Arrow $g 760 840 500 870 $theme.red 'Dash'; Badge $g 625 915 'Config + ACK'; Arrow $g 760 800 500 390 $theme.red 'Dash'; Badge $g 625 575 'Config + ACK'; Save $c '01_kien_truc_tong_the.png'
